apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-pplachy-tenant/devfile-sample-code-with-quarkus/devfile-sample-code-with-quarkus@sha256:946205609cc51fa0918e6022546a3f8f6b5b494997f0c25a69fc2abf6742f033
        name: my-java-quarkus
        resources: {}
status: {}
